### ISSUE TITLE
可以使用 UPM 方式托管

### ISSUE THREAD

**Issue by Bian-Sh** [CCEMT/UnityBindTool#3]
看起来这个仓库依赖了 Unity.Mathematics; 而这个不是一个默认的内置的插件，所以你的插件直接拖到工程目录下会报错。
使用 UPM 可以很好的处理这种依赖关系
同时也能自动安装依赖插件

**Comment by CCEMT** [comment]
我会考虑使用UPM来发布，但 Unity.Mathematics在Unity版本2021.3中是内置的，这个插件是在目标版本下开发的，还未考虑其他版本的运行，所以请先在目标版本使用

**Comment by Bian-Sh** [comment]
我用的就是 2021.3，应该不是内置，而是你用的某些插件依赖了它导致提前下载了。你可以创建全新工程导入你这个插件试试。

**Comment by CCEMT** [comment]
看来是我使用的是2D模板创建的项目，2D模板中确实是引用了Unity.Mathematics。在这个插件中Odin引用了Unity.Mathematics，Odin是属于付费插件，我忘记将它移除了，我重新发布了版本将Odin移除了，请自行导入Odin。因为这个插件并没有过多的依赖以及它只是一个小工具，所以我更倾向于把它放到工程目录下更易于管理与拓展，毕竟我做这个东西的初衷是让它作为一个小模块能够接入各种UI框架，所以暂时没有打算发布成UPM。
